url: "http://www.alextruesdale.net"
baseurl: ""

markdown: kramdown

assets:
  css_compressor: sass
  js_compressor: uglifier
  cache: false
  sources:
    - css
    - scripts
    - _assets
    - _assets/scss
    - _assets/js

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - gulpfile.js
  - README.md
  - _assets

tolerate_liquid_errors: false
