title: Alex Truesdale | Development & Design

description: Development & design for business applications.. and photos on occasion.

thumbnails:
  - image: /images/og_images/og_image_square.png
    type: image/png
    width: 600
    height: 600
  - image: /images/og_images/og_image_rect.png
    type: image/png
    width: 1200
    height: 630
