title: Alex Truesdale | Data & Development

description: Background in web design & development, now working in data science/analytics. Pursuing growth with boundless, interminable curiosity.

thumbnails:
  - image: /images/og_images/og_image_square.png
    type: image/png
    width: 600
    height: 600
  - image: /images/og_images/og_image_rect.png
    type: image/png
    width: 1200
    height: 630
